config/routes.rb
Mp::Application.routes.draw do
  resources :cleanings

  resources :pins

  devise_for :users
  root "pins#index"
  get "pricing" => "pages#pricing"
  get "where" => "pages#where"
  get "safety" => "pages#safety"
  get "book" => "pages#book"
  get "profile" => "pages#profile"
  get 'account' => "cleanings#account"
  get "analytics" => "pages#analytics"
 

end

app/models/cleaning.rb
class Cleaning < ActiveRecord::Base

	validates :month, :day, :hour, :minute, :ampm, presence: true

	belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
     belongs_to :user
     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
  has_many :cleanings
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name 
   devise_parameter_sanitizer.for(:sign_up) << :lastname
   devise_parameter_sanitizer.for(:sign_up) << :phone
   devise_parameter_sanitizer.for(:sign_up) << :address
   devise_parameter_sanitizer.for(:sign_up) << :city
   devise_parameter_sanitizer.for(:sign_up) << :zip
   devise_parameter_sanitizer.for(:sign_up) << :rooms
   devise_parameter_sanitizer.for(:sign_up) << :keys
   devise_parameter_sanitizer.for(:sign_up) << :trash
   devise_parameter_sanitizer.for(:sign_up) << :pets
   devise_parameter_sanitizer.for(:sign_up) << :parking
   devise_parameter_sanitizer.for(:sign_up) << :bedrooms
   devise_parameter_sanitizer.for(:sign_up) << :bathrooms
   devise_parameter_sanitizer.for(:sign_up) << :sf
   devise_parameter_sanitizer.for(:account_update) << :name 
   devise_parameter_sanitizer.for(:account_update) << :lastname 
   devise_parameter_sanitizer.for(:account_update) << :phone
   devise_parameter_sanitizer.for(:account_update) << :address
   devise_parameter_sanitizer.for(:account_update) << :city
   devise_parameter_sanitizer.for(:account_update) << :zip
   devise_parameter_sanitizer.for(:account_update) << :rooms
   devise_parameter_sanitizer.for(:account_update) << :keys
   devise_parameter_sanitizer.for(:account_update) << :trash
   devise_parameter_sanitizer.for(:account_update) << :pets
   devise_parameter_sanitizer.for(:account_update) << :parking
   devise_parameter_sanitizer.for(:account_update) << :bedrooms
   devise_parameter_sanitizer.for(:account_update) << :bathrooms
   devise_parameter_sanitizer.for(:account_update) << :sf
 end
end

app/controllers/cleanings_controller.rb
class CleaningsController < ApplicationController
  before_action :set_cleaning, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:account, :show, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def account
    @cleanings = Cleaning.where(user: current_user).order("created_at DESC").limit(3)
  end

  # GET /cleanings
  # GET /cleanings.json
  def index
    @cleanings = Cleaning.all.order("created_at DESC")
  end

  # GET /cleanings/1
  # GET /cleanings/1.json
  def show
  end

  # GET /cleanings/new
  def new
    @cleaning = Cleaning.new
  end

  # GET /cleanings/1/edit
  def edit
  end

  # POST /cleanings
  # POST /cleanings.json
  def create
    @cleaning = Cleaning.new(cleaning_params)
    @cleaning.user_id = current_user.id

    respond_to do |format|
      if @cleaning.save
        format.html { redirect_to account_path, notice: 'Cleaning was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cleaning }
      else
        format.html { render action: 'new' }
        format.json { render json: @cleaning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cleanings/1
  # PATCH/PUT /cleanings/1.json
  def update
    respond_to do |format|
      if @cleaning.update(cleaning_params)
        format.html { redirect_to @cleaning, notice: 'Cleaning was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cleaning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cleanings/1
  # DELETE /cleanings/1.json
  def destroy
    @cleaning.destroy
    respond_to do |format|
      format.html { redirect_to account_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cleaning
      @cleaning = Cleaning.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cleaning_params
      params.require(:cleaning).permit(:month, :day, :hour, :minute, :ampm, :focus, :frequency)
    end

    def check_user
      if current_user != @cleaning.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else."
      end
    end    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def pricing
  end
  def where
  end
  def book
  end
  def safety
  end
  def profile
  end
  def analytics
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
   @pins = Pin.all.order("created_at DESC").limit(12)
 end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :maid, :date, :neighborhood)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleanings_helper.rb
module CleaningsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/cleanings/account.html.erb
<div class="container">

<h3 class="cloudtext">Your Account&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;Welcome Back, <%= current_user.name %></h3>
<hr class="featurette-divider">

<div><button type="button" class="btn btn-default btn-lg"><%= link_to new_cleaning_path do %><span class="glyphicon glyphicon-calendar"></span>  Schedule your next cleaning<% end %></button></div>
</br>
<h4 class="cloudtext">Your most recently scheduled cleanings</h4>

<table class="table whiteback table-condensed table-bordered center">
  <tr>
      <th class="center belize">Date</th>
      <th class="center belize">Time</th>
      <th class="center belize">Cleaning Directions</th>
      <th class="center belize"></th>
  </tr>

    <% @cleanings.each do |cleaning| %>
      <tr>
        <td><% if cleaning.month == 1 %>
    <%= "January" %> 
    <% elsif cleaning.month == 2 %>
    <%= "February" %> 
    <% elsif cleaning.month == 3 %>
    <%= "March" %>  
    <% elsif cleaning.month == 4 %>
    <%= "April" %> 
    <% elsif cleaning.month == 5 %>
    <%= "May" %> 
    <% elsif cleaning.month == 6 %>
    <%= "June" %>
    <% elsif cleaning.month == 7 %>
    <%= "July" %>
    <% elsif cleaning.month == 8 %>
    <%= "August" %>
    <% elsif cleaning.month == 9 %>
    <%= "September" %>
    <% elsif cleaning.month == 10 %>
    <%= "October" %>
    <% elsif cleaning.month == 11 %>
    <%= "November" %>
    <% elsif cleaning.month == 12 %>
    <%= "December" %>
  <% end %>
  <%= cleaning.day %></td>
        <td><%= cleaning.hour %>:<% if cleaning.minute == 1 %>
    <%= "00" %> 
    <% else %>
      <%= "30" %>
    <% end %>
    <% if cleaning.ampm == 1 %>
       <%= "AM" %> 
    <% else %>
       <%= "PM" %>
    <% end %>
  </td>
        <td><%= cleaning.focus %></td>
        <td>
          <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Cancel Cleaning', cleaning, method: :delete, data: { confirm: 'Are you sure? Cancellations or reschedules within 24 hours of cleaning appointment will have a fee of $ 40.00' } %></li>
          </ul>
          </div>
        </td>
      </tr>
    <% end %>
</table>

<h4 class="cloudtext">Your Info</h4>
<%= render 'pages/customerinfo' %>
</div>

app/views/cleanings/edit.html.erb
<div class="container">

<h1>Editing cleaning</h1>

<%= render 'form' %>


<%= link_to 'Back', account_path %>


</div>

app/views/cleanings/index.html.erb
<div class="container">

<h1 class="cloudtext">All cleanings</h1>

<%= link_to 'New Cleaning', new_cleaning_path %>

<table class="table whiteback table-condensed table-bordered center">
  <tr>
      <th class="center">Date</th>
      <th class="center">Appointment Time</th>
      <th class="center">Hours</th>
      <th class="center">Customer Name</th>
      <th class="center">Address</th>
      <th class="center">Bedrooms</th>
      <th class="center">Cleaning Directions</th>
      <th class="center">Frequency</th>
      <<th class="center">Price</th>
      <th class="center"></th>
  </tr>

    <% @cleanings.each do |cleaning| %>
      <tr>
        <td><% if cleaning.month == 1 %>
    <%= "January" %> 
    <% elsif cleaning.month == 2 %>
    <%= "February" %> 
    <% elsif cleaning.month == 3 %>
    <%= "March" %>  
    <% elsif cleaning.month == 4 %>
    <%= "April" %> 
    <% elsif cleaning.month == 5 %>
    <%= "May" %> 
    <% elsif cleaning.month == 6 %>
    <%= "June" %>
    <% elsif cleaning.month == 7 %>
    <%= "July" %>
    <% elsif cleaning.month == 8 %>
    <%= "August" %>
    <% elsif cleaning.month == 9 %>
    <%= "September" %>
    <% elsif cleaning.month == 10 %>
    <%= "October" %>
    <% elsif cleaning.month == 11 %>
    <%= "November" %>
    <% elsif cleaning.month == 12 %>
    <%= "December" %>
  <% end %>
  <%= cleaning.day %></td>
        <td><%= cleaning.hour %>:<% if cleaning.minute == 1 %>
    <%= "00" %> 
    <% else %>
      <%= "30" %>
    <% end %>
    <% if cleaning.ampm == 1 %>
       <%= "AM" %> 
    <% else %>
       <%= "PM" %>
    <% end %>
  </td>

  <td><% if cleaning.user.sf == 1  %>
      <%= 2.5 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) %>
      <% elsif cleaning.user.sf == 2 %>
      <%= 2.5 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) + 0.5 %>
      <% elsif cleaning.user.sf == 3 %>
       <%= 2.5 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) + 1.5 %>
      <% elsif cleaning.user.sf == 4 %>
       <%= 2.5 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) + 3.5 %>
       <% elsif cleaning.user.sf == 5 %>
       <%= 2.5 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) + 5.5 %>
       <% elsif cleaning.user.sf == 6 %>
       <%= 2.5 + (current_user.bedrooms - 1 + cleaning.user.bathrooms - 1) + 7.5 %>
      <% elsif cleaning.user.sf == 7 %>
       <%= 2.5 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) + 8.5 %>
      <% end %> hours</td>

  <td><%= cleaning.user.name %> <%= cleaning.user.lastname %></td>
  <td><%= cleaning.user.address %>, <%= cleaning.user.city %>, <%= cleaning.user.zip %></td>
  <td><%= cleaning.user.bedrooms %>
        <td><%= cleaning.focus %></td>

        <td><% if cleaning.frequency == 1 %>
       <%= "One Time" %> 
    <% elsif cleaning.frequency == 2 %>
    <%= "Every 2 Weeks" %>
    <% elsif cleaning.frequency == 3 %>
    <%= "Every Week" %>
    <% elsif cleaning.frequency == 4 %>
    <%= "Every 3 Weeks" %>
    <% elsif cleaning.frequency == 5 %>
    <%= "Once a Month" %>
  <% end %></td>
  <td><% if cleaning.user.sf == 1  %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 %>
      <% elsif cleaning.user.sf == 2 %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 + 10 %>
      <% elsif cleaning.sf == 3 %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 + 30 %>
      <% elsif cleaning.user.sf == 4 %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 + 70 %>
       <% elsif cleaning.user.sf == 5 %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 + 110 %>
       <% elsif cleaning.user.sf == 6 %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 + 150 %>
      <% elsif cleaning.user.sf == 7 %>
      <%= 55 + (cleaning.user.bedrooms - 1 + cleaning.user.bathrooms - 1) * 10 + 190 %>
      <% end %></td>

        <td>
          <div class="btn-group">
          <button type="button" class="btn btn-info dropdown-toggle btn-sm" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Cancel Cleaning', cleaning, method: :delete, data: { confirm: 'Are you sure? Cancellations or reschedules within 24 hours of cleaning have a fee of $ 40.00' } %></li>
            <li><%= link_to 'Edit Cleaning', edit_cleaning_path(cleaning) %></li>
          </ul>
          </div>
        </td>
      </tr>
    <% end %>
</table>

</div>

app/views/cleanings/new.html.erb
<div class="container">



	<%= render 'form' %>



</div>

app/views/cleanings/show.html.erb
<p>
  <strong>Your Next Cleaning:</strong>
  <%= @cleaning.month %>
  <%= @cleaning.day %>
  <%= @cleaning.hour %>
  <%= @cleaning.minute %>
  <%= @cleaning.ampm %>
</p>

<%= link_to 'Edit', edit_cleaning_path(@cleaning) %> |
<%= link_to 'Back', cleanings_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "MaidPing", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
       <li><%= link_to "Where We Clean", where_path %></li>
      <li><%= link_to "Simple Pricing", pricing_path %></li> 
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><button type="button" class="btn btn-default navbar-btn"><%= link_to new_cleaning_path do %><span class="glyphicon glyphicon-calendar"></span>  Book a Maid Now<% end %></button></li>
          <li><%= link_to "My Account", account_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><button type="button" class="btn btn-default navbar-btn"><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-user"></span>  Already a Regular? Sign In<% end %></button></li>
        <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>
</nav>

app/views/pages/_homebottom.html.erb

<div class="container">
<hr class="featurette-divider">

<div class="row center">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail whiteback">
      <div class="caption">
        <h2 class="belize">The Best Maids in Los Angeles</h2>
        <p class="emerald">Easy Scheduling & Booking</p>
      </div>
     </div>
  </div>

<%= link_to pricing_path do %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail whiteback">
      <div class="caption">
        <h2 class="belize">Simple Pricing, Premium Cleaning</h2>
        <p class="emerald">100% Guaranteed</p>
      </div>
    </div>
  </div>
  <% end %>
  
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail whiteback">
      <div class="caption">
        <h2 class="belize">Every Maid & Cleaning Reviewed</h2>
        <p class="emerald">Backgrounds Checked, Bonded & Insured</p>
      </div>
    </div>
  </div>
</div>


<!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          </br>
        </br>
        </br>
          <h2 class="featurette-heading white">Finally, Maids that Rock! <span class="emerald">We'll amaze you.</span></h2>
          <p class="lead cloudtext">Getting a maid is usually a pain. Not with MaidPing. Just sign in, book your maid when you want your house cleaned and kick up your feet. Online, secure checkout.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive img-rounded img-thumbnail" data-src="holder.js/500x500/auto" <%= image_tag "lamaid4.jpg" %> 
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-responsive img-rounded img-thumbnail" data-src="holder.js/500x500/auto" <%= image_tag "lamaid5.jpg" %>
        </div>
        <div class="col-md-7">
          </br>
        </br>
        </br>
          <h2 class="featurette-heading white">Cleaning houses goes Hi-Tech! <span class="emerald">See the Clean.</span></h2>
          <p class="lead cloudtext">We reinvented the maid service. Push a couple of buttons, and your maid shows up on time. Relax. Simplicity at its best. Maid service that just works!</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
        </br>
        </br>
        </br>
          <h2 class="featurette-heading white">We Want to be your go-to Maids. <span class="emerald">Win-Win.</span></h2>
          <p class="lead cloudtext">We take your satisfaction seriously. Review your maid after each cleaning. We only keep the best maids. Your house cleaning is 100% guaranteed.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive img-rounded img-thumbnail" data-src="holder.js/500x500/auto" <%= image_tag "lamaid6.jpg" %> 
        </div>
      </div>

      <hr class="featurette-divider">
      

      <!-- /END THE FEATURETTES -->
    </div>







app/views/pages/_hometop.html.erb
<div class="jumbotron whiteback center">

  <div class="container">

	<h1 class="belize">Get Your Home Cleaned</h1>
  <h2 class="belize">You deserve it, <% if user_signed_in? %>
    <%= current_user.name do %><% end %><% else %> Los Angeles!</h2><% end %>

  </br>

	<div>
    <% if user_signed_in? %>
  </br>
	<button type="button" class="btn btn-default btn-lg"><%= link_to new_cleaning_path do %><span class="glyphicon glyphicon-calendar"></span>  Book a Maid Now <% end %></button>
    <% else %>
      <button type="button" class="btn btn-default btn-lg"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-calendar"></span>  Book a Maid Now <% end %></button>
      <% end %>
    </div>
 

  <%= link_to safety_path do %>
  <h4 class="text-muted center marg">&nbsp;&nbsp;&nbsp;&nbsp;Your home is your castle  &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-tower star"></span>&nbsp;&nbsp;&nbsp;  Learn about MaidPing safety</h4>
  <% end %>

</div>

</div>

app/views/pages/_profilemessage.html.erb
<div class="panel panel-default whiteback center belize">
  <div class="panel-body"><strong>
    Welcome Back, <%= current_user.name %></strong>
  </div>
</div>

app/views/pages/book.html.erb
<div class="jumbotron whiteback belize narrower">
<script type="text/javascript" src="https://www.formstack.com/forms/js.php?1663599-TnnaC16Qqj-v3"></script><noscript><a href="https://www.formstack.com/forms/?1663599-TnnaC16Qqj" title="Online Form">Online Form - Checkout</a></noscript>
</div>


app/views/pages/where.html.erb
<div class="container">
<h1 class="cloudtext center">We Clean all over LA</h1>

<div class="jumbotron center">
	<h2 class="center belize">Some of the LA Neighborhoods We Clean:</h2>

	<img class="img-thumbnail" <%= image_tag "DowntownLA.png"%>
	<h3 class="center belize">Downtown LA</h3>
</br>
	<img class="img-thumbnail" <%= image_tag "SantaMonica.png"%>
	<h3 class="center belize">Santa Monica</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "Pasadena.png"%>
	<h3 class="center belize">Pasadena</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "Belair.png"%>
	<h3 class="center belize">Bel Air</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "HollywoodHills.png"%>
	<h3 class="center belize">Hollywood and Hollywood Hills</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "Midcity.png"%>
	<h3 class="center belize">Miracle Mile</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "Venice.png"%>
	<h3 class="center belize">Venice</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "LosFelizSilverlake.png"%>
	<h3 class="center belize">Los Feliz and Silverlake</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "Koreatown.png"%>
	<h3 class="center belize">Koreatown</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "westwood.png"%>
	<h3 class="center belize">Westwood & UCLA</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "BeverlyHills.png"%>
	<h3 class="center belize">Beverly Hills</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "Glendale.png"%>
	<h3 class="center belize">Glendale</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "PacificPalisades.png"%>
	<h3 class="center belize">Pacific Palisades</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "USC.png"%>
	<h3 class="center belize">USC</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "WestHollywood.png"%>
	<h3 class="center belize">West Hollywood</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "CulverCity.png"%>
	<h3 class="center belize">Culver City</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "BrentwoodWestLA.png"%>
	<h3 class="center belize">Brentwood & West LA</h3>
	</br>
	<img class="img-thumbnail" <%= image_tag "CenturyCity.png"%>
	<h3 class="center belize">Century City</h3>
</div>	


<div class="jumbotron center narrow2">
	<h2 class="center belize">We clean almost anywhere around Los Angeles</h2>
<img class="img-rounded img-thumbnail" <%= image_tag "lamap.png"%>

</br>

 <% if user_signed_in? %>
  </br>
	<button type="button" class="btn btn-default btn-lg"><%= link_to new_cleaning_path do %><span class="glyphicon glyphicon-calendar"></span>  Book a Maid Now <% end %></button>
    <% else %>
      <button type="button" class="btn btn-default btn-lg"><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-calendar"></span>  Book a Maid Now <% end %></button>
      <% end %>
</div>
</div>



app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/hometop' %>


<h3 class="white center">Our Latest 5 Star Maid Reviews:</h3>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <img class="img-rounded" <%= image_tag pin.image.url(:thumb) %>
      <div class="panel-body center">
        <span class="glyphicon glyphicon-star star"></span><span class="glyphicon glyphicon-star star"></span><span class="glyphicon glyphicon-star star"></span><span class="glyphicon glyphicon-star star"></span><span class="glyphicon glyphicon-star star"></span>
      </br>
        <p><strong>Maid: <%= pin.maid %></strong></p>
        <p><%= pin.date %></p>
        <p><%= pin.neighborhood %></p>
        <p>"<%= pin.description %>"</p>
        <% if pin.user == current_user %>
          <%= link_to 'Show', pin_path(pin) %>
          <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<%= render 'pages/homebottom' %>